spring:
  application:
    name: user-service
  datasource:
    username: admin
    password: admin
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-db-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#custom settings
token:
  expiration-time: 3600000
  secret: randomlyGeneratedSecretTokenToSecureCovidApplication
