server:
  port: 8020

spring:
  devtools:
    restart:
      enabled: true
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

ribbon:
  eureka:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

#custom settings
token:
  secret: randomlyGeneratedSecretTokenToSecureCovidApplication

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer
