name: CD

on:
  push:
    branches: [ main ]

jobs:
  discovery:
    name: Discovery service
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Test
      run: mvn surefire:test --file ./back-end/discovery/pom.xml
        
    - name: Build
      run: mvn spring-boot:build-info --file ./back-end/discovery/pom.xml
      
    - name: Build docker image
      run: mvn spring-boot:build-image --file ./back-end/discovery/pom.xml
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push to DockerHub
      id: docker_build
      run: docker push gza73/simple-app-react-spring-jwt-back-end-discovery
          
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
