name: CD

on:
  push:
    branches: [ main ]

jobs:
  discovery:
    name: Discovery service
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Test
      run: mvn surefire:test --file ./back-end/discovery/pom.xml
        
    - name: Build
      run: mvn spring-boot:build-info --file ./back-end/discovery/pom.xml
